export const occupations = [
    'engineer',
    'politician',
    'baker',
    'butcher',
    'mechanic',
    'cook',
    'student',
    'dishwasher',
    'salesman',
    'sailor',
    'farmer',
    'clerk',
    'policeman',
    'nurse',
    'doctor',
    'barber',
    'candlestick maker',
    'taxi driver',
    'carpenter',
    'plumbler',
    'accountant',
    'attorney',
    'teacher'
];
